# Generated by Django 3.1.3 on 2020-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('name_of_project', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
